### ISSUE TITLE
playback.sh 不能生成正确的文件

### ISSUE THREAD

**Issue by z5n0w** [scue/android_tap_record#1]
sed报错

**Comment by scue** [comment]
你把报错信息贴出来下

**Comment by z5n0w** [comment]
./playback.sh 
触屏设备: /dev/input/event2 
sed: -e 表达式 #1, 字符 23: “s”的未知选项↵
使用Shell脚本执行:
  adb shell < send.sh >/dev/null
编译C语言文件执行: (推荐 - 高效, 少差错)
  arm-linux-androideabi-gcc send.c -o send

第155行出错了（其实sed可以用冒号做分割符的吧）

**Comment by scue** [comment]
可能是你的sed版本过旧吧，建议你使用ubuntu 12.04 + 的系统来操作。
